/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiposDocumentosRouteImport } from './routes/tipos-documentos'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as AnalistasRouteImport } from './routes/analistas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as EmpresasIdRouteImport } from './routes/empresas.$id'

const TiposDocumentosRoute = TiposDocumentosRouteImport.update({
  id: '/tipos-documentos',
  path: '/tipos-documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistasRoute = AnalistasRouteImport.update({
  id: '/analistas',
  path: '/analistas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresasRoute,
} as any)
const EmpresasIdRoute = EmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analistas': typeof AnalistasRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/tipos-documentos': typeof TiposDocumentosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analistas': typeof AnalistasRoute
  '/tipos-documentos': typeof TiposDocumentosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/empresas': typeof EmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analistas': typeof AnalistasRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/tipos-documentos': typeof TiposDocumentosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analistas'
    | '/empresas'
    | '/tipos-documentos'
    | '/empresas/$id'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analistas' | '/tipos-documentos' | '/empresas/$id' | '/empresas'
  id:
    | '__root__'
    | '/'
    | '/analistas'
    | '/empresas'
    | '/tipos-documentos'
    | '/empresas/$id'
    | '/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalistasRoute: typeof AnalistasRoute
  EmpresasRoute: typeof EmpresasRouteWithChildren
  TiposDocumentosRoute: typeof TiposDocumentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tipos-documentos': {
      id: '/tipos-documentos'
      path: '/tipos-documentos'
      fullPath: '/tipos-documentos'
      preLoaderRoute: typeof TiposDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analistas': {
      id: '/analistas'
      path: '/analistas'
      fullPath: '/analistas'
      preLoaderRoute: typeof AnalistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof EmpresasRoute
    }
    '/empresas/$id': {
      id: '/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof EmpresasIdRouteImport
      parentRoute: typeof EmpresasRoute
    }
  }
}

interface EmpresasRouteChildren {
  EmpresasIdRoute: typeof EmpresasIdRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
}

const EmpresasRouteChildren: EmpresasRouteChildren = {
  EmpresasIdRoute: EmpresasIdRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
}

const EmpresasRouteWithChildren = EmpresasRoute._addFileChildren(
  EmpresasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalistasRoute: AnalistasRoute,
  EmpresasRoute: EmpresasRouteWithChildren,
  TiposDocumentosRoute: TiposDocumentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
